server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127:0:0:1:8848
  application:
    name: nacos-consumer
feign:
  okhttp:
    enabled: true
