server:
  port: 8762
spring:
  application:
    name: eureka-server2
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 5000
#    use-read-only-response-cache: false
